"""update

Revision ID: 0777ae408f8e
Revises: edb2a826a65d
Create Date: 2025-08-16 10:36:18.651979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0777ae408f8e'
down_revision = 'edb2a826a65d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('PaymentMethod')
    # op.drop_table('category')
    # op.drop_table('country')
    # op.drop_table('orders')
    # op.drop_table('provinces')
    # op.drop_table('category_and_product')
    # op.drop_table('address_user')
    # op.drop_table('site_setting')
    # op.drop_table('coupons')
    # op.drop_table('brand-categorys')
    # op.drop_table('city')
    # op.drop_table('brands')
    with op.batch_alter_table('cart_products', schema=None) as batch_op:
        batch_op.alter_column('cartid',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('productid',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('permission_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('cartid',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('cartid',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.alter_column('permission_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('cart_products', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('productid',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('cartid',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.create_table('brands',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('brandcategory', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['brandcategory'], ['brand-categorys.id'], name=op.f('brands_brandcategory_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('brands_pkey')),
    sa.UniqueConstraint('name', name=op.f('brands_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('city',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('city_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('key', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('province', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['province'], ['provinces.id'], name='city_province_fkey'),
    sa.PrimaryKeyConstraint('id', name='city_pkey'),
    sa.UniqueConstraint('key', name='city_key_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('brand-categorys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('brand-categorys_pkey'))
    )
    op.create_table('coupons',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('coupons_pkey'))
    )
    op.create_table('site_setting',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('Value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('site_setting_pkey')),
    sa.UniqueConstraint('key', name=op.f('site_setting_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('address_user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('city', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=999), autoincrement=False, nullable=True),
    sa.Column('postal_code', sa.VARCHAR(length=999), autoincrement=False, nullable=True),
    sa.Column('User', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['User'], ['users.id'], name=op.f('address_user_User_fkey')),
    sa.ForeignKeyConstraint(['city'], ['city.id'], name=op.f('address_user_city_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('address_user_pkey'))
    )
    op.create_table('category_and_product',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('categoryid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('productid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['categoryid'], ['category.id'], name=op.f('category_and_product_categoryid_fkey')),
    sa.ForeignKeyConstraint(['productid'], ['products.id'], name=op.f('category_and_product_productid_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('category_and_product_pkey'))
    )
    op.create_table('provinces',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('country', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['country'], ['country.id'], name=op.f('provinces_country_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('provinces_pkey'))
    )
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cart', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('purchase_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cart'], ['carts.id'], name=op.f('orders_cart_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('orders_pkey'))
    )
    op.create_table('country',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('key', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('country_pkey')),
    sa.UniqueConstraint('key', name=op.f('country_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('category',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('category_pkey'))
    )
    op.create_table('PaymentMethod',
    sa.Column('authentication', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('payment_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('PaymentMethod_pkey')),
    sa.UniqueConstraint('payment_name', name=op.f('PaymentMethod_payment_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
