"""empty message

Revision ID: 18dd0e71260c
Revises: e5536ec48873
Create Date: 2025-10-18 09:44:24.267739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18dd0e71260c'
down_revision = 'e5536ec48873'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('street', sa.String(length=999), nullable=True))
        # batch_op.drop_constraint(batch_op.f('address_user_user_id_fkey'), type_='foreignkey')
        batch_op.drop_column('address')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=999), autoincrement=False, nullable=True))
        # batch_op.create_foreign_key(batch_op.f('address_user_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('street')

    # ### end Alembic commands ###
