"""adding address to orders

Revision ID: 4b35b545cb1c
Revises: 06dae4c67bc9
Create Date: 2025-10-12 16:58:56.214440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b35b545cb1c'
down_revision = '06dae4c67bc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('coupons')
    # op.drop_table('brand-categorys')
    # op.drop_table('cart_products')
    # op.drop_table('site_setting')
    # op.drop_table('PaymentMethod')
    # op.drop_table('brands')
    with op.batch_alter_table('address_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('address_user_User_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('address_user_city_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'city', ['city_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('city')
        batch_op.drop_column('User')

    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.add_column(sa.Column('province_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('city_province_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'provinces', ['province_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('province')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('cart_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_product'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_cart'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_order'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'])
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'])
        batch_op.create_foreign_key(None, 'carts', ['cart_id'], ['id'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'address_user', ['address'], ['id'])

    with op.batch_alter_table('provinces', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('provinces_country_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'country', ['country'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('permission_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.alter_column('permission_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('provinces', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('provinces_country_fkey'), 'country', ['country'], ['id'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('address')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_order'), 'orders', ['order_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_cart'), 'carts', ['cart_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_product'), 'products', ['product_id'], ['id'], ondelete='RESTRICT')
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('cart_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.add_column(sa.Column('province', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('city_province_fkey'), 'provinces', ['province'], ['id'])
        batch_op.drop_column('province_id')

    with op.batch_alter_table('address_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('User', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('city', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('address_user_city_fkey'), 'city', ['city'], ['id'])
        batch_op.create_foreign_key(batch_op.f('address_user_User_fkey'), 'users', ['User'], ['id'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('city_id')

    op.create_table('brands',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('brandcategory', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['brandcategory'], ['brand-categorys.id'], name=op.f('brands_brandcategory_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('brands_pkey')),
    sa.UniqueConstraint('name', name=op.f('brands_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('PaymentMethod',
    sa.Column('authentication', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('payment_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('PaymentMethod_pkey')),
    sa.UniqueConstraint('payment_name', name=op.f('PaymentMethod_payment_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('site_setting',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('Value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('site_setting_pkey')),
    sa.UniqueConstraint('key', name=op.f('site_setting_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('cart_products',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('cartid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('productid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cartid'], ['carts.id'], name=op.f('cart_products_cartid_fkey')),
    sa.ForeignKeyConstraint(['productid'], ['products.id'], name=op.f('cart_products_productid_fkey'))
    )
    op.create_table('brand-categorys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('brand-categorys_pkey'))
    )
    op.create_table('coupons',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('coupons_pkey'))
    )
    # ### end Alembic commands ###
