"""updating products

Revision ID: 673eac311810
Revises: 803d634cb099
Create Date: 2025-10-13 16:47:48.909108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '673eac311810'
down_revision = '803d634cb099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
