"""empty message

Revision ID: e5536ec48873
Revises: 673eac311810
Create Date: 2025-10-18 09:32:06.073630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5536ec48873'
down_revision = '673eac311810'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'address_user', ['address'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
