"""empty message

Revision ID: f7f5c208aa93
Revises: 18dd0e71260c
Create Date: 2025-10-18 16:21:01.101414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7f5c208aa93'
down_revision = '18dd0e71260c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('city_key_key'), type_='unique')
        batch_op.drop_column('key')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=999),
               existing_nullable=True)
        # batch_op.drop_constraint(batch_op.f('orders_address_fkey'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('orders_address_fkey'), 'address_user', ['address'], ['id'])
        batch_op.alter_column('address',
               existing_type=sa.String(length=999),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint(batch_op.f('city_key_key'), ['key'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
